[profile.default]
src = "src"
out = "out"
libs = ["lib", "src/lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

evm_version = "paris"
solc = "0.8.24"

scripts = [
  { name = "deploy:sepolia", cmd = "script script/Counter.s.sol:Counter --broadcast --rpc-url ${SEPOLIA_RPC_URL}" }
]