[profile.default]
src = "contracts"
out = "out"
libs = ['node_modules', 'lib']
cache_path  = 'cache-forge'
test = 'test-forge'
solc = "0.8.24"
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
